data:
  image: busybox:latest
  volumes:
    - /opt/dbdata
db:
  image: postgres:latest
  volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  volumes_from:
    - data
  ports:
    - "5432:5432"
web:
  build: .
  volumes:
    - .:/app
  ports:
    - "3000:3000"
    - "35729:35729"    
  links:
    - db

  
